name: Mention
version: ${project.version}
main: net.kunlab.mention.Mention
api-version: 1.16
authors: [ Bun133 ]
description: This plugin will provide mention system like Discord
website: https://twitter.com/bun133_
